# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld/helloworld.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld/helloworld.proto',
  package='feed',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bhelloworld/helloworld.proto\x12\x04\x66\x65\x65\x64\"\x07\n\x05\x45mpty\"\x1f\n\x0c\x46\x65\x65\x64Response\x12\x0f\n\x07message\x18\x01 \x01(\t2;\n\x06\x46\x65\x65\x64\x65r\x12\x31\n\nGetNewFeed\x12\x0b.feed.Empty\x1a\x12.feed.FeedResponse\"\x00\x30\x01\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='feed.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=44,
)


_FEEDRESPONSE = _descriptor.Descriptor(
  name='FeedResponse',
  full_name='feed.FeedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='feed.FeedResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['FeedResponse'] = _FEEDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'helloworld.helloworld_pb2'
  # @@protoc_insertion_point(class_scope:feed.Empty)
  })
_sym_db.RegisterMessage(Empty)

FeedResponse = _reflection.GeneratedProtocolMessageType('FeedResponse', (_message.Message,), {
  'DESCRIPTOR' : _FEEDRESPONSE,
  '__module__' : 'helloworld.helloworld_pb2'
  # @@protoc_insertion_point(class_scope:feed.FeedResponse)
  })
_sym_db.RegisterMessage(FeedResponse)



_FEEDER = _descriptor.ServiceDescriptor(
  name='Feeder',
  full_name='feed.Feeder',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=79,
  serialized_end=138,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetNewFeed',
    full_name='feed.Feeder.GetNewFeed',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_FEEDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FEEDER)

DESCRIPTOR.services_by_name['Feeder'] = _FEEDER

# @@protoc_insertion_point(module_scope)
